### ISSUE TITLE
Nullable fields

### ISSUE THREAD

**Issue by JayBizzle** [Naoray/laravel-factory-prefill#11]
Just wondering what the reason is for ignoring `nullable` fields.

https://github.com/Naoray/laravel-factory-prefill/blob/451158cbed30451ad9336216090b7bcb87250a02/src/Commands/PrefillFactory.php#L92

Thanks

**Comment by Naoray** [comment]
I was aiming to show just the required fields in the factory. I am open for a PR to add a flag for including `nullable` fields.
