### ISSUE TITLE
Consider lazy() method for relationship

### ISSUE THREAD

**Issue by ludo237** [Naoray/laravel-factory-prefill#2]
Hello.

First of all, great package!

I've noticed that relationships are generated using and [old method](https://github.com/Naoray/laravel-factory-prefill/blob/master/src/Commands/PrefillFactory.php#L150). Have you considered using `factory(App\REPLACE_THIS::class)->lazy();` instead? 

It should not be a problem since the package is targeting illuminate 5.7 and `lazy()` is present since 5.5

**Comment by Naoray** [comment]
Hello @ludo237,

thanks for pointing this out! Didn't know a `lazy()` method existed. Added it in v1.0.1
