### ISSUE TITLE
Required 5.8 and above?

### ISSUE THREAD

**Issue by Braunson** [Naoray/laravel-factory-prefill#8]
I understand the support for 5.8+ but some of us right now are not able to update due to dependencies stuck on 5.7, any way to support 5.7 for the time being?

**Comment by Naoray** [comment]
5.7 is supported. Try `compiser require naoray/laravel-factory-prefill:1.0`

**Comment by Naoray** [comment]
Tbh I dont know how to support both (5.7, 5.8) at the same time. If you could assist on that it d be really nice

**Comment by Braunson** [comment]
Yep will create a PR :)

**Comment by Braunson** [comment]
Done @Naoray 😄

**Comment by Naoray** [comment]
Thank you @Braunson! v1.1.1 release Now is for both versions of laravel
